language: rust

jobs:
    include:
        - rust: stable
          install:
            - rustup component add rustfmt
            - rustup component add clippy

          script:
          - tests/pre-commit.sh
          # upload coverage statistics to codecov.io
          env: RUSTFLAGS="-C link-dead-code"
          addons:
            apt:
              packages:
                - libcurl4-openssl-dev
                - libelf-dev
                - libdw-dev
                - cmake
                - gcc
                - binutils-dev
                - libiberty-dev
                - libssl-dev
          before_cache: cargo install cargo-tarpaulin
          # cache ~/.cargo explicitly so that ./target isn't cached
          cache:
              directories:
                  - $HOME/.cargo
          after_success: |
              cargo tarpaulin --out Xml &&
              bash <(curl -s https://codecov.io/bash) &&
              echo "Uploaded code coverage"

        - rust: beta
          # sometimes rustfmt changes its mind about formatting between releases
          script: cargo test

        - rust: nightly
          # afl needs nightly
          script:
            - cargo test
            - tests/fuzz.sh
