[package]
name = "rcc"
version = "0.1.0"
authors = ["Joshua Nelson <jyn514@gmail.com>"]
edition = "2018"
description = "A C compiler written in Rust, with a focus on good error messages."
repository = "https://github.com/jyn514/rcc/"
readme ="README.md"
categories = ["parser-implementations"]
license = "BSD-3-Clause"

[dependencies]
lazy_static = "1"
ansi_term = "0.12"
cranelift = "0.44"
cranelift-faerie = "0.44"
cranelift-module = "0.44"
failure = "0.1"
target-lexicon = "0.8"
tempfile = "3"
pico-args = "0.3"

[profile.release]
lto = true

[profile.dev]
debug = false  # speeds up link time

[profile.test]
debug = false
