[package]
name = "rcc"
version = "0.5.0"
authors = ["Joshua Nelson <jyn514@gmail.com>", "Graham Scheaffer <me@gisch.dev>"]
edition = "2018"
description = "A C compiler written in Rust, with a focus on good error messages."
repository = "https://github.com/jyn514/rcc/"
readme = "README.md"
categories = ["development-tools", "parser-implementations"]
license = "BSD-3-Clause"
keywords = ["C", "compiler", "recursive-descent", "cranelift"]
default-run = "rcc"

[dependencies]
lazy_static = "1"
ansi_term = "0.12"
cranelift = "0.58"
cranelift-module = "0.58"
cranelift-object = "0.58"
cranelift-simplejit = "0.58"
env_logger = { version = "0.7", default-features = false }
hexf-parse = "0.1"
thiserror = ">=1.0.9"
log = "0.4"
target-lexicon = "0.10"
tempfile = "3"
pico-args = "0.3"
string-interner = "0.7"
codespan = "0.7"
color-backtrace = { version = "0.3", default-features = false }

[dev-dependencies]
criterion = "0.3.1"
walkdir = "2"

[[bench]]
name = "examples"
harness = false

[profile.release]
lto = true

[profile.test]
debug = false  # speeds up link time

[profile.bench]
opt-level = 3
debug = false
lto = true
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false
