[package]
name = "compiler"
version = "0.1.0"
authors = ["Joshua Nelson <jyn514@gmail.com>"]
edition = "2018"
description = "A C compiler written in Rust, with a focus on good error messages."

[dependencies]
lazy_static = "1"
ansi_term = "0.11"
structopt = "0.2"
