[package]
name = "compiler"
version = "0.1.0"
authors = ["Joshua Nelson <jyn514@gmail.com>"]
edition = "2018"
description = "A C compiler written in Rust, with a focus on good error messages."
repository = "https://github.com/jyn514/rcc/"
readme ="README.md"
categories = ["parser-implementations"]
license = "BSD-3-Clause"

[dependencies]
lazy_static = "1"
ansi_term = "0.11"
cranelift = "0.40"
cranelift-faerie = "0.40"
cranelift-module = "0.40"
failure = "0.1"
target-lexicon = "0.4"
tempfile = "3"
pico-args = "0.2"

[profile.release]
lto = true
