[package]
name = "rcc"
version = "0.4.0"
authors = ["Joshua Nelson <jyn514@gmail.com>", "Graham Scheaffer <me@gisch.dev>"]
edition = "2018"
description = "A C compiler written in Rust, with a focus on good error messages."
repository = "https://github.com/jyn514/rcc/"
readme = "README.md"
categories = ["development-tools", "parser-implementations"]
license = "BSD-3-Clause"
keywords = ["C", "compiler", "recursive-descent", "cranelift"]

[dependencies]
lazy_static = "1"
ansi_term = "0.12"
cranelift = "0.56"
cranelift-module = "0.56"
cranelift-object = "0.56"
env_logger = "0.7"
hexf-parse = "0.1"
thiserror = ">=1.0.9"
log = "0.4"
target-lexicon = "0.10"
tempfile = "3"
pico-args = "0.3"
string-interner = "0.7"
codespan = "0.7"

[dev-dependencies]
walkdir = "2"

[profile.release]
lto = true

[profile.dev]
debug = false  # speeds up link time

[profile.test]
debug = false
